/*
 * This file is generated by scripts/generate-props.js.
 * Do not edit manually.
 */

export type VueDraggableProp = {
  name: string
  component: 'Draggable' | 'DraggableCore'
  inheritedFrom?: 'DraggableCore' | null
  definedIn: 'draggableProps' | 'draggableCoreProps' | 'draggableCoreDefaultProps'
  vueRuntimeTypes: string[]
  tsType: string | null
  sourceType: string | null
  default: string | null
  hasDefault: boolean
  defaultIsFactory: boolean
  required: boolean | null
  validator: string | null
  source: { file: string }
  description: string
}

export const DRAGGABLE_CORE_PROPS: VueDraggableProp[] = [
  {
    "name": "allowAnyClick",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Allows drag with any mouse button",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "disabled",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Disables dragging",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "allowMobileScroll",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Allows mobile scrolling (touch events won't prevent default)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScroll",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Enables auto-scrolling at edges",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollThreshold",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "30",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Distance from edge to trigger auto-scroll (pixels)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollMaxSpeed",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "20",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Maximum auto-scroll speed",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollAxis",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "Axis",
    "default": "'both'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String as PropType<Axis>",
    "description": "Auto-scroll direction",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollIncludeWindow",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Whether auto-scroll includes window",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollContainer",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Object",
      "String",
      "Array"
    ],
    "tsType": "AutoScrollContainerProp",
    "default": "null",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "[Object, String, Array] as PropType<AutoScrollContainerProp>",
    "description": "Auto-scroll container",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "cancelInteractiveElements",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Disable dragging on interactive elements (input, textarea, etc.)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "enableClickSuppression",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Suppress click events after dragging",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "clickSuppressionDuration",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "250",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Click suppression duration (ms)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragStartThreshold",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "0",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Minimum drag distance to trigger drag (pixels)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragStartDelay",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "0",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Delay before drag starts (ms)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragStartDelayTolerance",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "5",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Tolerance for movement during drag delay (pixels)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "enableUserSelectHack",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Enable hack to prevent text selection",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "useRafDrag",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Use requestAnimationFrame for performance optimization",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "startFn",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Function"
    ],
    "tsType": "(e: DraggableEvent, data: DraggableData) => void | false",
    "default": "noop",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Function as PropType<(e: DraggableEvent, data: DraggableData) => void | false>",
    "description": "Drag start callback. Return false to cancel.",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragFn",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Function"
    ],
    "tsType": "(e: DraggableEvent, data: DraggableData) => void | false",
    "default": "noop",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Function as PropType<(e: DraggableEvent, data: DraggableData) => void | false>",
    "description": "Drag move callback. Return false to cancel.",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "stopFn",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Function"
    ],
    "tsType": "(e: DraggableEvent, data: DraggableData) => void | false",
    "default": "noop",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Function as PropType<(e: DraggableEvent, data: DraggableData) => void | false>",
    "description": "Drag stop callback",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "scale",
    "component": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "1",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Scale factor (for internal scaling)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "cancel",
    "component": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "description": "Selector to prevent dragging",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "offsetParent",
    "component": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "HTMLElement",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": "(value: unknown): boolean => propIsNotNode(value)",
    "sourceType": "Object as PropType<HTMLElement>",
    "description": "Offset parent element",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "grid",
    "component": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "Array"
    ],
    "tsType": "number[]",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Array as PropType<number[]>",
    "description": "Grid for snapping, e.g. [25, 25]",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "handle",
    "component": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "description": "Selector for drag handle",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "nodeRef",
    "component": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "HTMLElement | null",
    "default": "() => null",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<HTMLElement | null>",
    "description": "Node reference",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  }
]

export const DRAGGABLE_PROPS: VueDraggableProp[] = [
  {
    "name": "allowAnyClick",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Allows drag with any mouse button",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "disabled",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Disables dragging",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "allowMobileScroll",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Allows mobile scrolling (touch events won't prevent default)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScroll",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Enables auto-scrolling at edges",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollThreshold",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "30",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Distance from edge to trigger auto-scroll (pixels)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollMaxSpeed",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "20",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Maximum auto-scroll speed",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollAxis",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "Axis",
    "default": "'both'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String as PropType<Axis>",
    "description": "Auto-scroll direction",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollIncludeWindow",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Whether auto-scroll includes window",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "autoScrollContainer",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Object",
      "String",
      "Array"
    ],
    "tsType": "AutoScrollContainerProp",
    "default": "null",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "[Object, String, Array] as PropType<AutoScrollContainerProp>",
    "description": "Auto-scroll container",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "cancelInteractiveElements",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Disable dragging on interactive elements (input, textarea, etc.)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "enableClickSuppression",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Suppress click events after dragging",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "clickSuppressionDuration",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "250",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Click suppression duration (ms)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragStartThreshold",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "0",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Minimum drag distance to trigger drag (pixels)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragStartDelay",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "0",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Delay before drag starts (ms)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragStartDelayTolerance",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "5",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Tolerance for movement during drag delay (pixels)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "enableUserSelectHack",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Enable hack to prevent text selection",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "useRafDrag",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Use requestAnimationFrame for performance optimization",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "startFn",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Function"
    ],
    "tsType": "(e: DraggableEvent, data: DraggableData) => void | false",
    "default": "noop",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Function as PropType<(e: DraggableEvent, data: DraggableData) => void | false>",
    "description": "Drag start callback. Return false to cancel.",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "dragFn",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Function"
    ],
    "tsType": "(e: DraggableEvent, data: DraggableData) => void | false",
    "default": "noop",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Function as PropType<(e: DraggableEvent, data: DraggableData) => void | false>",
    "description": "Drag move callback. Return false to cancel.",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "stopFn",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Function"
    ],
    "tsType": "(e: DraggableEvent, data: DraggableData) => void | false",
    "default": "noop",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Function as PropType<(e: DraggableEvent, data: DraggableData) => void | false>",
    "description": "Drag stop callback",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "scale",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreDefaultProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "1",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Scale factor (for internal scaling)",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "cancel",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "description": "Selector to prevent dragging",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "offsetParent",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "HTMLElement",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": "(value: unknown): boolean => propIsNotNode(value)",
    "sourceType": "Object as PropType<HTMLElement>",
    "description": "Offset parent element",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "grid",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "Array"
    ],
    "tsType": "number[]",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Array as PropType<number[]>",
    "description": "Grid for snapping, e.g. [25, 25]",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "handle",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "description": "Selector for drag handle",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "nodeRef",
    "component": "Draggable",
    "inheritedFrom": "DraggableCore",
    "definedIn": "draggableCoreProps",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "HTMLElement | null",
    "default": "() => null",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<HTMLElement | null>",
    "description": "Node reference",
    "source": {
      "file": "lib/DraggableCore.tsx"
    }
  },
  {
    "name": "axis",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "Axis",
    "default": "'both'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String as PropType<Axis>",
    "description": "Restricts drag direction ('x', 'y', or 'both')",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "directionLock",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "description": "Locks drag to the direction of the first movement",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "directionLockThreshold",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "4",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "description": "Threshold in pixels for direction locking",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "bounds",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "Object",
      "String",
      "Boolean"
    ],
    "tsType": "DraggableBounds",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "[Object, String, Boolean] as PropType<DraggableBounds>",
    "description": "Drag bounds. Can be a selector, 'parent', object, or false",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "defaultClassName",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "'vue-draggable'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "description": "Default class name",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "defaultClassNameDragging",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "'vue-draggable-dragging'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "description": "Class name while dragging",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "defaultClassNameDragged",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "'vue-draggable-dragged'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "description": "Class name after drag stops",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "defaultPosition",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "ControlPosition",
    "default": "() => ({ x: 0, y: 0 })",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<ControlPosition>",
    "description": "Initial position (only used at initialization)",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "positionOffset",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "PositionOffsetControlPosition",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<PositionOffsetControlPosition>",
    "description": "Position offset",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  },
  {
    "name": "position",
    "component": "Draggable",
    "inheritedFrom": null,
    "definedIn": "draggableProps",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "ControlPosition",
    "default": "undefined",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<ControlPosition>",
    "description": "Controlled position. Must be updated via dragFn when set",
    "source": {
      "file": "lib/Draggable.tsx"
    }
  }
]
