/*
 * This file is generated by scripts/generate-props.js.
 * Do not edit manually.
 */

export const VUE_DRAGGABLE_TYPE_DEFS = {
  "Axis": "type Axis = 'both' | 'x' | 'y' | 'none';",
  "DraggableBounds": "interface DraggableBounds {\n  left?: number;\n  right?: number;\n  top?: number;\n  bottom?: number;\n}",
  "ControlPosition": "interface ControlPosition {x: number, y: number}",
  "PositionOffsetControlPosition": "interface PositionOffsetControlPosition {x: number|string, y: number|string}",
  "DraggableEvent": "type DraggableEvent = MouseEvent | TouchEvent | PointerEvent",
  "DraggableData": "interface DraggableData {\n  node: HTMLElement,\n  x: number, y: number,\n  deltaX: number, deltaY: number,\n  lastX: number, lastY: number\n}",
  "AutoScrollContainerInput": "type AutoScrollContainerInput = HTMLElement | Window | string",
  "AutoScrollContainerProp": "type AutoScrollContainerProp = AutoScrollContainerInput | AutoScrollContainerInput[] | null"
} as const

export type VueDraggableTypeName = keyof typeof VUE_DRAGGABLE_TYPE_DEFS
